/**
 * Public exports to hide from the API reference.
 *
 * Add any symbol name here to drop it from the API sidebar, catalog, and
 * generated pages. References to it in remaining pages are unlinked to plain
 * text automatically. A symbol is only worth excluding when nothing else
 * links to it from the guide (e.g. Realm schema internals, big constant
 * tables). Re-run `npm run docs:build` (or `docs:manifest` + `docs:excludes`)
 * after changing this list.
 */
export const apiExcludes: string[] = [
  // Internal query classes used by the public result types.
  'EntityQuery',
  'BeatmapQuery',
  'CollectionQuery',
  'FileQuery',
  'KeyBindingQuery',
  'MetadataQuery',
  'ModPresetQuery',
  'RulesetQuery',
  'RulesetSettingQuery',
  'ScoreQuery',
  'SetQuery',
  'SkinQuery',
  'QuerySnapshot',
  'QuerySurface',
  'WriteOps',
  'BatchWrite',
  'ResultFacade',
  'EditableResultFacade',
  'Beatmaps',
  'Sets',
  'Scores',
  'Collections',
  'Rulesets',
  'RulesetSettings',
  'Skins',
  'Files',
  'Keybindings',
  'ModPresets',
  'Metadata',
  'DeepMutable',
  'DeepReadonly',
  'BeatmapPatch',
  'BeatmapSetPatch',
  'CollectionPatch',
  'ScorePatch',
  'SkinPatch',
  'FilePatch',
  'KeyBindingPatch',
  'ModPresetPatch',
  'RulesetPatch',
  'BeatmapEdit',
  'BeatmapSetEdit',
  'CollectionEdit',
  'FileEdit',
  'KeyBindingEdit',
  'ModPresetEdit',
  'RulesetEdit',
  'ScoreEdit',
  'SkinEdit',
  // Internal Realm schema definitions.
  'Schema',
  'BeatmapSchema',
  'BeatmapSetSchema',
  'BeatmapCollectionSchema',
  'BeatmapDifficultySchema',
  'BeatmapMetadataSchema',
  'BeatmapUserSettingsSchema',
  'FileSchema',
  'KeyBindingSchema',
  'ModPresetSchema',
  'RealmNamedFileUsageSchema',
  'RealmUserSchema',
  'RulesetSchema',
  'RulesetSettingSchema',
  'ScoreSchema',
  'SkinSchema',
  // Internal built-in skin data.
  'BUILT_IN_SKINS',
  'BUILT_IN_SKIN_IDS',
  'BUILT_IN_SKIN_ORDER',
  // Data constants such as key binding tables and schema versions. Public enums remain documented.
  'GLOBAL_DEFAULTS',
  'OSU_DEFAULTS',
  'TAIKO_DEFAULTS',
  'CATCH_DEFAULTS',
  'RulesetAction',
  'MIN_SCHEMA_VERSION',
  'CURRENT_SCHEMA_VERSION',
]
