export default {
  entryPoints: ['src/index.ts'],
  entryPointStrategy: 'resolve',
  tsconfig: 'tsconfig.json',
  plugin: ['typedoc-plugin-markdown'],
  out: 'docs/api/generated',
  json: 'docs/.generated/typedoc.json',
  excludeInternal: true,
  excludePrivate: true,
  excludeProtected: true,
  excludeExternals: true,
  categorizeByGroup: true,
  includeVersion: true,
  sourceLinkTemplate: 'https://github.com/heyngra/osu-files/blob/{gitRevision}/{path}#L{line}',
  parametersFormat: 'table',
  enumMembersFormat: 'table',
  hideBreadcrumbs: true,
  hidePageHeader: true,
  useHTMLAnchors: true,
}
