export type KeyBindingDef = {
  action: number
  keyCombination: string
}

export const GlobalAction = {
  ToggleChat: 0,
  ToggleSocial: 1,
  ResetInputSettings: 2,
  ToggleToolbar: 3,
  ToggleSettings: 4,
  ToggleBeatmapListing: 5,
  IncreaseVolume: 6,
  DecreaseVolume: 7,
  ToggleMute: 8,
  SkipCutscene: 9,
  QuickRetry: 10,
  TakeScreenshot: 11,
  ToggleGameplayMouseButtons: 12,
  Back: 13,
  IncreaseScrollSpeed: 14,
  DecreaseScrollSpeed: 15,
  Select: 16,
  QuickExit: 17,
  MusicNext: 18,
  MusicPrev: 19,
  MusicPlay: 20,
  ToggleNowPlaying: 21,
  SelectPrevious: 22,
  SelectNext: 23,
  Home: 24,
  ToggleNotifications: 25,
  PauseGameplay: 26,
  EditorSetupMode: 27,
  EditorComposeMode: 28,
  EditorDesignMode: 29,
  EditorTimingMode: 30,
  HoldForHUD: 31,
  RandomSkin: 32,
  TogglePauseReplay: 33,
  ToggleInGameInterface: 34,
  ToggleModSelection: 35,
  SelectNextRandom: 36,
  SelectPreviousRandom: 37,
  ToggleBeatmapOptions: 38,
  EditorVerifyMode: 39,
  EditorNudgeLeft: 40,
  EditorNudgeRight: 41,
  ToggleSkinEditor: 42,
  PreviousVolumeMeter: 43,
  NextVolumeMeter: 44,
  SeekReplayForward: 45,
  SeekReplayBackward: 46,
  ToggleChatFocus: 47,
  EditorCycleGridSpacing: 48,
  EditorTestGameplay: 49,
  EditorFlipHorizontally: 50,
  EditorFlipVertically: 51,
  EditorIncreaseDistanceSpacing: 52,
  EditorDecreaseDistanceSpacing: 53,
  ActivatePreviousSet: 54,
  ActivateNextSet: 55,
  DeselectAllMods: 56,
  EditorTapForBPM: 57,
  ToggleFPSDisplay: 58,
  ToggleProfile: 59,
  EditorCloneSelection: 60,
  EditorCyclePreviousBeatSnapDivisor: 61,
  EditorCycleNextBeatSnapDivisor: 62,
  SaveReplay: 63,
  ExportReplay: 64,
  ToggleReplaySettings: 65,
  ToggleInGameLeaderboard: 66,
  EditorToggleRotateControl: 67,
  IncreaseOffset: 68,
  DecreaseOffset: 69,
  StepReplayForward: 70,
  StepReplayBackward: 71,
  IncreaseModSpeed: 72,
  DecreaseModSpeed: 73,
  EditorToggleScaleControl: 74,
  EditorTestPlayToggleAutoplay: 75,
  EditorTestPlayToggleQuickPause: 76,
  EditorTestPlayQuickExitToInitialTime: 77,
  EditorTestPlayQuickExitToCurrentTime: 78,
  EditorSeekToPreviousHitObject: 79,
  EditorSeekToNextHitObject: 80,
  EditorSeekToPreviousSamplePoint: 81,
  EditorSeekToNextSamplePoint: 82,
  EditorCycleGridType: 83,
  EditorAddBookmark: 84,
  EditorRemoveClosestBookmark: 85,
  EditorSeekToPreviousBookmark: 86,
  EditorSeekToNextBookmark: 87,
  AbsoluteScrollSongList: 88,
  EditorToggleMoveControl: 89,
  EditorDiscardUnsavedChanges: 90,
  ExpandPreviousGroup: 91,
  ExpandNextGroup: 92,
  ToggleCurrentGroup: 93,
  PreviousSkin: 94,
  NextSkin: 95,
  EditorSubmitBeatmap: 96,
  EditorEditExternally: 97,
  FastForwardReplay: 98,
} as const

export const OsuAction = {
  LeftButton: 0,
  RightButton: 1,
  Smoke: 2,
} as const

export const TaikoAction = {
  LeftRim: 0,
  LeftCentre: 1,
  RightCentre: 2,
  RightRim: 3,
} as const

export const CatchAction = {
  MoveLeft: 0,
  MoveRight: 1,
  Dash: 2,
} as const

export const ManiaAction = {
  Key1: 0, Key2: 1, Key3: 2, Key4: 3, Key5: 4,
  Key6: 5, Key7: 6, Key8: 7, Key9: 8, Key10: 9,
  Key11: 10, Key12: 11, Key13: 12, Key14: 13, Key15: 14,
  Key16: 15, Key17: 16, Key18: 17, Key19: 18, Key20: 19,
} as const

export const RulesetName = {
  Osu: 'osu',
  Taiko: 'taiko',
  Fruits: 'fruits',
  Mania: 'mania',
} as const

export type RulesetShortName = 'osu' | 'taiko' | 'fruits' | 'mania' | (string & {})

export const RulesetOnlineID = {
  Osu: 0,
  Taiko: 1,
  Fruits: 2,
  Mania: 3,
} as const

export const RulesetAction = {
  osu: OsuAction,
  taiko: TaikoAction,
  fruits: CatchAction,
  mania: ManiaAction,
} as const
