import { test, expect } from '@playwright/test'

test('interactive examples start as readable previews and load on demand', async ({ page }) => {
  const workerRequests: string[] = []
  page.on('request', request => { if (request.url().includes('worker')) workerRequests.push(request.url()) })
  await page.goto('/')
  const preview = page.locator('.promotable-example').first()
  await expect(preview.locator('.promotable-example__activate')).toBeVisible()
  await expect(preview.locator('.language-ts.vp-adaptive-theme')).toBeVisible()
  await expect(preview.locator('.language-ts.vp-adaptive-theme .lang')).toHaveText('ts')
  await expect(preview.locator('.language-ts.vp-adaptive-theme .vp-code')).toBeVisible()
  await expect(preview.locator('.language-ts.vp-adaptive-theme .vp-code .line')).not.toHaveCount(0)
  await expect(preview.locator('.language-ts.vp-adaptive-theme .vp-code span[style*="--shiki-"]')).not.toHaveCount(0)
  await expect(preview.locator('.api-example__preview')).toHaveCount(0)
  await expect(preview.locator('.api-example__bar')).toHaveCount(0)
  const activate = preview.locator('.promotable-example__activate')
  const copy = preview.locator('.language-ts.vp-adaptive-theme > .copy')
  await expect(activate).toHaveCSS('opacity', '0')
  await expect(copy).toHaveCSS('opacity', '0')
  await preview.locator('.language-ts.vp-adaptive-theme pre').hover()
  await expect(activate).toHaveCSS('opacity', '1')
  await expect(copy).toHaveCSS('opacity', '1')
  await page.locator('h1').first().hover()
  await expect(activate).toHaveCSS('opacity', '0')
  await expect(copy).toHaveCSS('opacity', '0')
  await expect(page.locator('.api-example')).toHaveCount(0)
  await expect(page.locator('.monaco-editor')).toHaveCount(0)
  expect(workerRequests.some(url => url.includes('ts.worker'))).toBe(false)

  await activate.click()
  const example = page.locator('.api-example').first()
  await expect(example.locator('.monaco-editor')).toBeVisible({ timeout: 20_000 })
  await expect(example.locator('.api-example__run')).toBeEnabled()
  await expect(example.locator('.monaco-editor .view-lines')).toContainText("from 'osu-files'")
  await expect(example.locator('.monaco-editor .view-lines')).not.toContainText('@docs/fixture')
  await expect(example.locator('.monaco-editor .view-lines')).not.toContainText('export default function run')
  expect(workerRequests.some(url => url.includes('ts.worker'))).toBe(true)
})

test('loaded examples execute and reset', async ({ page }) => {
  await page.goto('/')
  const preview = page.locator('.promotable-example').first()
  await preview.locator('.promotable-example__activate').click()
  const example = page.locator('.api-example').first()
  const editor = example.locator('.monaco-editor')
  await expect(editor).toBeVisible({ timeout: 20_000 })
  await editor.click()
  await page.keyboard.press('Control+Home')
  await page.keyboard.type("console.log('edited')\n")
  await example.getByRole('button', { name: 'Run' }).click()
  await expect(example.locator('.api-example__console')).toContainText('edited')
  await example.getByRole('button', { name: 'Reset' }).click()
  await example.getByRole('button', { name: 'Confirm' }).click()
  await expect(editor.locator('.view-lines')).not.toContainText('edited')
})

test('returned JSON renders as a collapsible tree', async ({ page }) => {
  await page.goto('/')
  const preview = page.locator('.promotable-example').first()
  await preview.locator('.promotable-example__activate').click()
  const example = page.locator('.api-example').first()
  const editor = example.locator('.monaco-editor')
  await expect(editor).toBeVisible({ timeout: 20_000 })
  await editor.click()
  await page.keyboard.press('Control+A')
  await page.keyboard.type("return { nested: { title: 'Fixture' }, values: [1, true], nothing: null, emptyObject: {}, emptyArray: [] }")
  await example.getByRole('button', { name: 'Run' }).click()

  const output = example.locator('[data-json-output]')
  await expect(output).toBeVisible()
  const root = output.locator('[data-json-node="object"][data-json-depth="0"]')
  await expect(root).toHaveAttribute('open')

  const nested = output.locator('[data-json-node="object"][data-json-depth="1"]').first()
  await expect(nested).not.toHaveAttribute('open')
  await expect(nested.locator('[data-json-node="string"]')).toBeHidden()
  await nested.locator('summary').click()
  await expect(nested).toHaveAttribute('open')
  await expect(nested.locator('[data-json-node="string"]')).toBeVisible()
  await expect(output.locator('[data-json-path="$.emptyObject"]')).toHaveText('"emptyObject":{}')
  await expect(output.locator('[data-json-path="$.emptyArray"]')).toHaveText('"emptyArray":[]')
  await expect(output.locator('details[data-json-path="$.emptyObject"], details[data-json-path="$.emptyArray"]')).toHaveCount(0)
})

test('non-JSON output keeps the plain-text fallback', async ({ page }) => {
  await page.goto('/')
  const preview = page.locator('.promotable-example').first()
  await preview.locator('.promotable-example__activate').click()
  const example = page.locator('.api-example').first()
  const editor = example.locator('.monaco-editor')
  await expect(editor).toBeVisible({ timeout: 20_000 })
  await editor.click()
  await page.keyboard.press('Control+A')
  await page.keyboard.type('return undefined')
  await example.getByRole('button', { name: 'Run' }).click()

  const output = example.locator('[data-json-output]')
  await expect(output.locator('.output-panel__fallback')).toContainText('undefined')
  await expect(output.locator('[data-json-node]')).toHaveCount(0)
})

test('loaded editor and edits persist for the current tab session', async ({ page }) => {
  await page.goto('/')
  const preview = page.locator('.promotable-example').first()
  await preview.locator('.promotable-example__activate').click()
  const example = page.locator('.api-example').first()
  const editor = example.locator('.monaco-editor')
  await expect(editor).toBeVisible({ timeout: 20_000 })
  await editor.click()
  await page.keyboard.press('Control+End')
  await page.keyboard.type('\nconst sessionEdit = true')
  await page.reload()
  const restoredPreview = page.locator('.promotable-example').first()
  await expect(restoredPreview.locator('.language-ts.vp-adaptive-theme')).toBeVisible()
  await expect(page.locator('.api-example')).toHaveCount(0)
  await restoredPreview.locator('.promotable-example__activate').click()
  const restoredExample = page.locator('.api-example').first()
  const restored = restoredExample.locator('.monaco-editor')
  await expect(restored).toBeVisible({ timeout: 20_000 })
  await expect(restored.locator('.view-lines')).toContainText('sessionEdit')
})

test('Monaco reports TypeScript and docs lint errors after loading', async ({ page }) => {
  await page.goto('/')
  const preview = page.locator('.promotable-example').first()
  await preview.locator('.promotable-example__activate').click()
  const example = page.locator('.api-example').first()
  const editor = example.locator('.monaco-editor')
  await expect(editor).toBeVisible({ timeout: 20_000 })
  await editor.click()
  await page.keyboard.press('Control+A')
  await page.keyboard.type("import { parseOsu } from 'osu-files'\nimport fs from 'node:fs'\n\nconst value = parseOsu(beatmaps[0].osuText).metadta")
  await expect(example.locator('.api-example__diagnostics')).toContainText("Property 'metadta' does not exist")
  await expect(example.locator('.api-example__diagnostics')).toContainText('Only the public osu-files import')
  await expect(example.getByRole('button', { name: 'Run' })).toBeDisabled()
})

test('Monaco provides library completions after loading', async ({ page }) => {
  await page.goto('/')
  const preview = page.locator('.promotable-example').first()
  await preview.locator('.promotable-example__activate').click()
  const example = page.locator('.api-example').first()
  const editor = example.locator('.monaco-editor')
  await expect(editor).toBeVisible({ timeout: 20_000 })
  await editor.click()
  await page.keyboard.press('Control+A')
  await page.keyboard.type("import { parseOsu } from 'osu-files'\nconst beatmap = parseOsu(beatmaps[0].osuText)\nbeatmap.")
  await page.keyboard.press('Control+Space')
  await expect(page.locator('.suggest-widget')).toContainText('metadata')
  await expect(page.locator('.suggest-widget')).toContainText('hitObjects')
})

test('fixture facade examples load without TypeScript diagnostics', async ({ page }) => {
  await page.goto('/api/facades/Beatmaps')
  const preview = page.locator('.promotable-example').first()
  await expect(preview.locator('.promotable-example__activate')).toBeVisible()
  await preview.locator('.promotable-example__activate').click()
  const example = page.locator('.api-example[data-execution="interactive-fixture"]').first()
  await expect(example.locator('.monaco-editor')).toBeVisible({ timeout: 20_000 })
  await expect(example.locator('.api-example__diagnostics')).toContainText('No problems detected.')
  await expect(example.locator('.api-example__diagnostics [data-error]')).toHaveCount(0)
})

test('facade edit examples keep independent TypeScript module scopes', async ({ page }) => {
  await page.goto('/api/facades/Beatmaps')

  for (const id of ['facade-Beatmaps-autoEdit', 'facade-Beatmaps-commit', 'facade-Beatmaps-rollback']) {
    const example = page.locator(`#${id}`)
    await example.locator('.promotable-example__activate').click()
    await expect(example.locator('.monaco-editor')).toBeVisible({ timeout: 20_000 })
  }

  for (const id of ['facade-Beatmaps-autoEdit', 'facade-Beatmaps-commit', 'facade-Beatmaps-rollback']) {
    const diagnostics = page.locator(`#${id} .api-example__diagnostics`)
    await expect(diagnostics).toContainText('No problems detected.')
    await expect(diagnostics).not.toContainText('Cannot redeclare block-scoped variable')
  }
})

test('facade array results stay structured after running', async ({ page }) => {
  await page.goto('/api/facades/Beatmaps')
  const preview = page.locator('.promotable-example').first()
  await preview.locator('.promotable-example__activate').click()
  const example = page.locator('.api-example[data-execution="interactive-fixture"]').first()
  await expect(example.locator('.monaco-editor')).toBeVisible({ timeout: 20_000 })
  const output = example.locator('[data-json-output]')
  await expect(output.locator('[data-json-node="array"][data-json-depth="0"]')).toBeVisible()
  await expect(output.locator('[data-json-path="$[0].title"]')).toHaveText('"title":"Make A Move"')
  await expect(example.getByRole('button', { name: 'Run (Ctrl+Enter)' })).toBeEnabled()
  await example.getByRole('button', { name: 'Run (Ctrl+Enter)' }).click()

  await expect(output.locator('.output-panel__fallback')).toHaveCount(0)
  await expect(output.locator('[data-json-node="array"][data-json-depth="0"]')).toBeVisible()
  await expect(output.locator('[data-json-path="$[0].title"]')).toHaveText('"title":"Make A Move"')
})
